name: Python application

on:
  push:
    # To allow CI debugging we trigger on the CI branch
    branches:
    - CI
    
    # Publish `1.2.3` tags as releases.
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

  pull_request:
    branches:
    - master
  
  

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check Format with Black
      run: |
        pip install black
        # We will fail if we are not formatted with black
        python -m black --check --target-version py37 --line-length 127 source/
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
      env:
        PYTHONPATH: source/
    - name: Build dists
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
